### PR TITLE
chore: update `urlpattern-polyfill`

### LINKED ISSUE #266: update `urlpattern-polyfill`

### PR DESCRIPTION
**Pull request by SettingDust**
fix #266

### CODE REVIEW

**Comment by ndaidong** [comment]
@SettingDust hi friend, why we shouldn't keep the old style?

`src/utils/findRulesByUrl.js`
```js
import { URLPattern } from 'urlpattern-polyfill'
```

Can you describe the problem you found here?

**Comment by SettingDust** [comment]
There isn't `URLPattern` export from it in newer version.
https://github.com/kenchris/urlpattern-polyfill/blob/main/src/index.d.ts#L3-L8=

**Comment by ndaidong** [comment]
@SettingDust sorry, I have not much experience with TypeScript.  Does this problem affect only to TypeScript environment, or Node.js too?  I still see they still mention to `URLPattern` at README, does that mean they missed something?

https://github.com/kenchris/urlpattern-polyfill#loading-as-esm-module

I found that they export `URLPattern` for Node.js environment:

https://github.com/kenchris/urlpattern-polyfill/blob/main/index.js#L3

**Comment by SettingDust** [comment]
But the types not export the classes. So the completion is broken

**Comment by ndaidong** [comment]
@SettingDust ok, thank you.

**Pull request merged**
